### ISSUE TITLE
Add tests for the SEARCH commands

### ISSUE THREAD

**Issue by BagritsevichStepan** [dragonflydb/dragonfly#4204]
We should not crash during parsing different options in `FT.*` commands. For example: (empty separator in FT.CREATE)
```
127.0.0.1:6379> ft.create index on json schema $.sometag AS sometag TAG SEPARATOR
Error: Server closed the connection
```

So we should add parsing tests for all `FT.*` commands, especially for the `FT.CREATE`, `FT.SEARCH` and `FT.AGGREGATE` commands.

- [x] #4208
- [x] Add tests for different options in the `FT.CREATE` command. Fixed by #4678
- [x] Add tests for different options in the `FT.SEARCH` command. Fixed by #4478
- [x] Add tests for different options in the `FT.AGGREGATE` command. Fixed by #4479
- [ ] Test all other FT.* commands
